### ISSUE TITLE
change oci-factory release strategy to drop patch

### ISSUE THREAD

**Issue by shipperizer** [canonical/identity-platform-admin-ui#450]
a couple of CVE came up #448 #449

we should revise how we do releases and drop the patch part on the tag so that we are better able to perform patches and have the very same tag updated using the current release workflow

https://github.com/canonical/identity-platform-admin-ui/blob/main/.github/workflows/publish.yaml#L94

the oci-factory cli should output something like 

```
    - source: canonical/identity-platform-admin-ui
      commit: d40b55c5689d0671dbca2c54829bdfb543917985
      directory: ./
      release:
        1.21-22.04:
            end-of-life: "2024-11-07T00:00:00Z"
            risks:
                - candidate
                - edge
``` 

so `v<major>.<minor>` and drop the patch
